### ISSUE TITLE
Issues in ToLoFirrtl and ModuleLevelDiagrammer

### ISSUE THREAD

**Issue by racast** [chick/visualizer#19]
Hi, 

I tried to use our tool to create a fir.svg image for my project. However, when I run it I have the following errors : 

[error] /home/visualizer/src/main/scala/dotvisualizer/ToLoFirrtl.scala:40: not found: value Shlw
[error]       case prim @ DoPrim(Shlw,_,_,_) => prim.copy(op = Shl)
[error]                          ^
[error] /home/visualizer/src/main/scala/dotvisualizer/transforms/ModuleLevelDiagrammer.scala:129: type mismatch;
[error]  found   : firrtl.ir.Statement => Unit
[error]  required: Unit => Unit
[error]           module map InstanceGraph.collectInstances(set)
[error]                                                    ^
[error] /home/visualizer/src/main/scala/dotvisualizer/transforms/ModuleLevelDiagrammer.scala:129: No implicit view available from Unit => Unit => firrtl.Mappers.ModuleMagnet.
[error]           module map InstanceGraph.collectInstances(set)
[error]                  ^
[error] three errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 7 s, completed 10 mars 2019 18:31:31

Best regards.

**Comment by chick** [comment]
I can take a look tomorrow, but I think this is due to a slightly older version of firrtl. I'd suggest trying to clear the ivy's cached and local directories  for edu.berkeley.cs, and trying to re-run.

**Comment by racast** [comment]
I tried, but I still have the same issues.

**Comment by chick** [comment]
I see. This is the older version of the diagrammer. I need to deprecate this repo. 
The current version of diagrammer is [freechipsproject/diagrammer](https://github.com/freechipsproject/diagrammer).
Can you tell me how you found your way to this repo, and I will try and fix the references to point to the new repo. 
Thanks, sorry for the confusion.

**Comment by racast** [comment]
Hi, 

I just googled "chisel vizualiser" because I saw something link to it in a old GitHub project. 
Sorry about it. 
Thank you very much for your help.
